#include<stdio.h>

#define something_that_make_your_brain_explode int
#define mainframe_computer_thats_how_skynet_has_made main
#define herewego return
#define kirat ;
#define nothing_nothing_just_nothing_its_just_nothing 0
#define whatisthis "%d"
#define have_some_rest ,
#define the_answer_to_life_the_universe_and_everything 42
#define show_this_quote_to_users printf
#define openthegualhogualhogualgualho (
#define closethegualhogualhogualgualho )
#define OPENTHEGUALHOGUALHOGUALGUALHO {
#define CLOSETHEGUALHOGUALHOGUALGUALHO }
#define PROTOCOL101_GOTO_THE_NEXT_LINE_MOVE_MOVE_MOVE "\n"

something_that_make_your_brain_explode mainframe_computer_thats_how_skynet_has_made openthegualhogualhogualgualho closethegualhogualhogualgualho OPENTHEGUALHOGUALHOGUALGUALHO
  show_this_quote_to_users openthegualhogualhogualgualho whatisthis have_some_rest the_answer_to_life_the_universe_and_everything closethegualhogualhogualgualho kirat
  show_this_quote_to_users openthegualhogualhogualgualho PROTOCOL101_GOTO_THE_NEXT_LINE_MOVE_MOVE_MOVE closethegualhogualhogualgualho kirat
  herewego nothing_nothing_just_nothing_its_just_nothing  kirat
CLOSETHEGUALHOGUALHOGUALGUALHO
